os: linux
dist: bionic
arch:
  - ppc64le

language: c

services:
  - docker

env:
  global:
    - GITHUB_REPO=pmem/pmdk
    - DOCKERHUB_REPO=ldorau/pmdk
    - MAKE_PKG=0
    - PMDK_CC=gcc
    - PMDK_CXX=g++
    - REMOTE_TESTS=0
    - VALGRIND=1
    - SRC_CHECKERS=0
    - EXPERIMENTAL=n
  jobs:
    - OS=archlinux-base OS_VER=latest TEST_BUILD=debug
    - OS=centos OS_VER=7 TEST_BUILD=debug
    - OS=centos OS_VER=8 TEST_BUILD=debug
    - OS=debian OS_VER=testing TEST_BUILD=debug PMDK_CC=clang-9 PMDK_CXX=clang++-9
    - OS=debian OS_VER=unstable TEST_BUILD=debug PMDK_CC=clang-9 PMDK_CXX=clang++-9
    - OS=fedora OS_VER=rawhide TEST_BUILD=debug
    - OS=opensuse-leap OS_VER=latest TEST_BUILD=debug
    - OS=opensuse-tumbleweed OS_VER=latest TEST_BUILD=debug
    - OS=ubuntu OS_VER=rolling TEST_BUILD=debug

before_install:
  - echo $TRAVIS_COMMIT_RANGE
  - export HOST_WORKDIR=`pwd`
  - cd utils/docker
  - ./pull-or-rebuild-image.sh

script:
  - images/push-image.sh

after_success:
  - date
