os: linux
dist: bionic
arch:
  - ppc64le

language: c

services:
  - docker

env:
  global:
    - GITHUB_REPO=pmem/pmdk
    - DOCKERHUB_REPO=ldorau/pmdk
    - MAKE_PKG=0
    - PMDK_CC=gcc
    - PMDK_CXX=g++
    - REMOTE_TESTS=1
    - VALGRIND=1
    - SRC_CHECKERS=0
    - EXPERIMENTAL=n
  jobs:
    - OS=archlinux-base OS_VER=latest TEST_BUILD=debug

before_install:
  - echo $TRAVIS_COMMIT_RANGE
  - export HOST_WORKDIR=`pwd`
  - cd utils/docker
  - ./pull-or-rebuild-image.sh

script:
  - ./build-CI.sh

after_success:
  - source ./set-vars.sh
  - if [[ -f $CI_FILE_PUSH_IMAGE_TO_REPO ]]; then ./images/push-image.sh; fi
