name: PMDK
on: [push]

env:
    GITHUB_REPO:    pmem/pmdk
    DOCKERHUB_REPO: pmem/pmdk
    HOST_WORKDIR:   /home/runner/work/pmdk/pmdk
    WORKDIR:        utils/docker
    # global variables
    PMDK_CC:        gcc
    PMDK_CXX:       g++
    MAKE_PKG:       0
    REMOTE_TESTS:   0
    VALGRIND:       1

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CONFIG: ["OS=fedora OS_VER=31    PMDK_CC=clang PMDK_CXX=clang++ TEST_BUILD=debug",
                 "OS=fedora OS_VER=31    PMDK_CC=clang PMDK_CXX=clang++ TEST_BUILD=nondebug AUTO_DOC_UPDATE=1",
                 "OS=fedora OS_VER=31    MAKE_PKG=1 EXPERIMENTAL=y REMOTE_TESTS=0 VALGRIND=0 PUSH_IMAGE=1",
                 "OS=ubuntu OS_VER=19.10 COVERAGE=1 FAULT_INJECTION=1 TEST_BUILD=debug",
                 "OS=ubuntu OS_VER=19.10 FAULT_INJECTION=1 TEST_BUILD=debug",
                 "OS=ubuntu OS_VER=19.10 FAULT_INJECTION=1 TEST_BUILD=nondebug",
                 "OS=ubuntu OS_VER=19.10 PMDK_CC=clang PMDK_CXX=clang++ TEST_BUILD=debug",
                 "OS=ubuntu OS_VER=19.10 PMDK_CC=clang PMDK_CXX=clang++ TEST_BUILD=nondebug",
                 "OS=ubuntu OS_VER=19.10 MAKE_PKG=1 EXPERIMENTAL=y REMOTE_TESTS=0 VALGRIND=0 NDCTL_ENABLE=n PUSH_IMAGE=1",
                 "OS=ubuntu OS_VER=19.10 MAKE_PKG=1 EXPERIMENTAL=y REMOTE_TESTS=0 VALGRIND=0 NDCTL_ENABLE=n PMDK_CC=clang PMDK_CXX=clang++",
                 "OS=ubuntu OS_VER=19.10 COVERITY=1"]
    steps:
       - name: Clone the git repo
         uses: actions/checkout@v1

       - name: Change ownership of the repo
         run: sudo chown -R 1000.1000 $HOST_WORKDIR

       - name: Pull or rebuild the image
         run: cd $WORKDIR && ${{ matrix.CONFIG }} ./pull-or-rebuild-image.sh

       - name: Run the build
         run: cd $WORKDIR && ${{ matrix.CONFIG }} ./build-travis.sh

       - name: Push the image
         run: cd $WORKDIR && ${{ matrix.CONFIG }} /bin/bash -c "if [[ -f push_image_to_repo_flag ]]; then images/push-image.sh $OS-$OS_VER; fi"
