#
# The 'XXX_DISABLE_' suffix is used twice in this file to disable two actions:
# 1) XXX_DISABLE_${CI_FILE_PUSH_IMAGE_TO_REPO} - disables pushing the rebuilt Docker image and
# 2) XXX_DISABLE_AUTO_DOC_UPDATE - disables making pull requests with the update of documentation.
# Those two actions are disabled, because they conflict with the same ones run on Travis.
# Only one CI (Travis or GitHub Actions) can run them at the time, so they can be enabled here,
# when we decide to switch from Travis to GitHub Actions. The 'XXX_DISABLE_' suffix should be removed then.
#

name: test WIN
on: [push, pull_request]

env:
    GITHUB_REPO:    pmem/pmdk
    DOCKERHUB_REPO: pmem/pmdk

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    env:
      platform: x64
      solutionname: PMDK.sln
      ex_solutionname: Examples.sln
      msbuild: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin"
      # Platform Toolset for Visual Studio 2019
      platform_toolset: "v142"
      perl: "C:\\Strawberry\\perl\\bin"
    strategy:
      matrix:
        CONFIG: [Debug] # , Release]
    steps:
       - name: Update Path
         run: |
           echo "::add-path::$Env:msbuild"
           echo "::add-path::$Env:perl"

       - name: Cache PMDK
         uses: actions/cache@v1
         id: cache-pmdk
         with:
            path: D:/a/pmdk
            key:  pmdk-2

       - name: Clone the git repo
         uses: actions/checkout@v2
         with:
           clean: false

       - name: Various debug checks (cstyle, whitespace etc.)
         if: steps.cache-pmdk.outputs.cache-hit != 'true'
         run: |
           if ("${{ matrix.CONFIG }}" -eq "Debug")
           {
              Install-Module PsScriptAnalyzer -Force
              utils/CSTYLE.ps1
              if ($LASTEXITCODE -ne 0) {
                 exit 1
              }
              utils/CHECK_WHITESPACE.ps1
              if ($LASTEXITCODE -ne 0) {
                 exit 1
              }
              utils/ps_analyze.ps1
              if ($LASTEXITCODE -ne 0) {
                 exit 1
              }
              perl utils/sort_solution check
              if ($LASTEXITCODE -ne 0) {
                 exit 1
              }
              ./utils/check_sdk_version.py -d .
              if ($LASTEXITCODE -ne 0) {
                 exit 1
              }
           }

       - name: Build
         if: steps.cache-pmdk.outputs.cache-hit != 'true'
         run: |
           msbuild src\$Env:solutionname -property:Configuration=${{ matrix.CONFIG }},PlatformToolset=$Env:platform_toolset -m -v:m
           msbuild src\examples\$Env:ex_solutionname -property:Configuration=${{ matrix.CONFIG }},PlatformToolset=$Env:platform_toolset -m -v:m

       - name: Create ZIP archive
         if: steps.cache-pmdk.outputs.cache-hit != 'true'
         run: utils/CREATE-ZIP.ps1 -b ${{ matrix.CONFIG }}

       - name: Run tests
         if: steps.cache-pmdk.outputs.cache-hit == 'true'
         shell: powershell
         run: |
           if ($true) {
               cd src\test
               echo "`$Env:NON_PMEM_FS_DIR = `"C:\temp`"" >> testconfig.ps1
               echo "`$Env:PMEM_FS_DIR = `"C:\temp`"" >> testconfig.ps1
               echo "`$Env:PMEM_FS_DIR_FORCE_PMEM = `"1`"" >> testconfig.ps1
               echo "`$Env:PMDK_NO_ABORT_MSG = `"1`"" >> testconfig.ps1
               echo "`$Env:TM = `"1`"" >> testconfig.ps1
               write-output "config = {'unittest_log_level': 1, 'pmem_fs_dir': 'C:\\temp', 'non_pmem_fs_dir': 'C:\\temp', 'tm': True, 'test_type': 'check', 'fs': 'all', 'fs_dir_force_pmem': 1, 'keep_going': False, 'timeout': '4m', 'build': 'debug', 'force_enable': None}" | out-file "testconfig.py" -encoding utf8

               if ("${{ matrix.CONFIG }}" -eq "Debug") {
                   ./RUNTESTS.ps1 -b debug -o 4m
                   if ($?) {
                       ./RUNTESTS.py -b debug
                   }
               }
               if ("${{ matrix.CONFIG }}" -eq "Release") {
                   ./RUNTESTS.ps1 -b nondebug -o 4m
                   if ($?) {
                       ./RUNTESTS.py -b release
                   }
               }
           }
