name: PMDK
on: [push, pull_request]

env:
    GITHUB_REPO:    pmem/pmdk
    DOCKERHUB_REPO: pmem/pmdk

jobs:
  windows:
    name: Windows
    runs-on: windows-latest
    env:
      platform: x64
      solutionname: PMDK.sln
      ex_solutionname: Examples.sln
      msbuild: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin"
      perl: "C:\\Strawberry\\perl\\bin"
    strategy:
      matrix:
        CONFIG: [Debug] # , Release]
    steps:
       - name: Update PATH
         run: |
           echo "::add-path::$Env:perl"
           echo "::add-path::$Env:msbuild"

       - name: Print PATH
         run: echo "PATH=$Env:PATH"

       - name: Install Text::Diff
         run: cpanm Text::Diff

       - run: Install-Module PsScriptAnalyzer -Force
#       - run: Install-PackageProvider -Name NuGet -Force

       - name: Clone the git repo
         uses: actions/checkout@v1

       - name: before_build
         run: |
           if ("${{ matrix.CONFIG }}" -eq "Debug")
           {
              utils/CSTYLE.ps1
              if ($LASTEXITCODE -ne 0) {
                 exit 1
              }
              utils/CHECK_WHITESPACE.ps1
              if ($LASTEXITCODE -ne 0) {
                 exit 1
              }
              utils/ps_analyze.ps1
              if ($LASTEXITCODE -ne 0) {
                 exit 1
              }
              perl utils/sort_solution check
              if ($LASTEXITCODE -ne 0) {
                 exit 1
              }
              ./utils/check_sdk_version.py -d .
              if ($LASTEXITCODE -ne 0) {
                 exit 1
              }
           }
